"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gg@e3i*3+)!&e9fa9h887uuxxjc9@1!=gk(71ej=7&k31hf%7v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS=[
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS=[
    'content-type',
    'authorization',
    'x-requested-with',
    'accept',
]

# Additional CORS settings for media files
CORS_EXPOSE_HEADERS = [
    'content-type',
    'content-disposition',
]
# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django_q',
    'accounts',
    'lead',
    
]


Q_CLUSTER = {
    'name': 'DjangoQ',
    'workers': 2,                  # keep low to save RAM
    'recycle': 500,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',     
    'broker_class': 'django_q.brokers.redis_broker.Redis',
    'redis': {
        'host': '127.0.0.1',
        'port': 6379,
        'db': 0,
    },
    'schedule_types': {
        'minutes': 60,
        'repeats': -1
    },
    'scheduled': [
        {
            'name': 'Follow-up Reminders',
            'func': 'lead.tasks.send_follow_up_reminders',
            'schedule': 'daily',
            'repeats': -1,
        },
        {
            'name': 'Check Overdue Tasks',
            'func': 'lead.tasks.check_overdue_tasks',
            'schedule': '0 */2 * * *',  # Every 2 hours
            'repeats': -1,
        },
        {
            'name': 'Meeting Reminders 24hrs',
            'func': 'lead.tasks.send_meeting_reminders_24hrs',
            'schedule': '0 * * * *',  # Every hour
            'repeats': -1,
        },
        {
            'name': 'Meeting Reminders 1hr',
            'func': 'lead.tasks.send_meeting_reminders_1hr',
            'schedule': '*/30 * * * *',  # Every 30 minutes
            'repeats': -1,
        },
        {
            'name': 'Check Payment Due Reminders',
            'func': 'lead.tasks.check_payment_due_reminders',
            'schedule': 'daily',
            'repeats': -1,
        },
        {
            'name': 'Check High-Value Deals',
            'func': 'lead.tasks.check_high_value_deals',
            'schedule': '0 */6 * * *',  # Every 6 hours
            'repeats': -1,
        },
        {
            'name': 'Re-engagement Emails',
            'func': 'lead.tasks.send_re_engagement_emails',
            'schedule': '0 2 * * 1',  # Every Monday at 2 AM
            'repeats': -1,
        },
        {
            'name': 'Birthday Campaigns',
            'func': 'lead.tasks.check_birthday_campaigns',
            'schedule': 'daily',
            'repeats': -1,
        },
    ]
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'crm.middleware.CorsMediaMiddleware',  # Custom middleware for media CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    #   "default": {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'crm',
    #     'USER': 'root',
    #     'PASSWORD':'hariharan@512',
    #     'HOST': 'localhost',
    #     'PORT': '3306'
    # },
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "mydatabase",
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crm',
        'USER': 'root',
        'PASSWORD':'root',
        'HOST': 'localhost',
        'PORT': '3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SPECTACULAR_SETTINGS = {
    'TITLE': 'CRM API',
    'DESCRIPTION': 'API documentation for CRM',
    'VERSION': '1.0.0',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}
from datetime import timedelta

SIMPLE_JWT={
    'ACCESS_TOKEN_LIFETIME':timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME':timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    # Allow users with is_active=False to authenticate using JWT tokens
    # (controls rest_framework_simplejwt behaviour)
    'CHECK_USER_IS_ACTIVE': False,
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # For Gmail SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'marketing4repute@gmail.com' # Your email address
EMAIL_HOST_PASSWORD = 'ewke vjvn mnrv tluc'

# Frontend URL for email links
FRONTEND_URL = 'https://brandhunt.in/'  # Update this to your frontend URL

# Default from email
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

GOOGLE_SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR, 'artful-hexagon-497606-e2-b3e8e23a8b14.json')
# Calendar ID to use (use 'primary' or a calendar email)
GOOGLE_CALENDAR_ID = 'repute.hariharan@gmail.com'
