# Generated by Django 5.1.2 on 2024-12-08 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lead_source_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_source_from',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.lead_source'),
        ),
    ]
