# Generated by Django 5.1.2 on 2025-01-17 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_teams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teams",
            name="bde_user",
        ),
        migrations.AddField(
            model_name="teams",
            name="bde_user",
            field=models.ManyToManyField(
                related_name="bde_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
