# Generated by Django 5.1.2 on 2025-01-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teams_bdm_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='probability',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
