# Generated by Django 5.2 on 2025-10-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_monthlytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
