# Generated by Django 5.2 on 2025-10-31 04:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usertarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertarget',
            unique_together={('user', 'target')},
        ),
    ]
