# Generated by Django 5.2 on 2025-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usertarget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertarget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
