# Generated by Django 4.2.11 on 2025-11-08 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_usertarget_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_targets', to=settings.AUTH_USER_MODEL),
        ),
    ]
