# Generated by Django 5.2 on 2026-06-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_useractivehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivehistory',
            name='changed_at',
            field=models.DateTimeField(),
        ),
    ]
