# Generated by Django 5.1.2 on 2024-10-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_task_log_task_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity_stage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
