# Generated by Django 5.1.2 on 2024-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lead', '0009_alter_opportunity_stage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.tag'),
        ),
    ]
