# Generated by Django 5.1.2 on 2024-12-07 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0012_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="assinged_to",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_type",
            field=models.CharField(
                choices=[
                    ("Digital Lead", "Digital Lead"),
                    ("Manual Lead", "Manual Lead"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
