# Generated by Django 5.1.2 on 2024-12-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0014_contact_is_primary_log_lead_log_opportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead.contact",
            ),
        ),
    ]
