# Generated by Django 5.1.2 on 2024-12-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0015_opportunity_primary_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
