# Generated by Django 5.1.2 on 2024-12-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_lead_source_from"),
        ("lead", "0016_alter_contact_is_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.contact_status",
            ),
        ),
    ]
