# Generated by Django 5.1.2 on 2024-12-07 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_lead_source_from"),
        ("lead", "0017_alter_contact_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="lead_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.lead_source",
            ),
        ),
    ]
