# Generated by Django 5.1.2 on 2024-12-07 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0018_alter_contact_lead_source"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="assinged_to",
            new_name="assigned_to",
        ),
    ]
