# Generated by Django 5.1.2 on 2024-12-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_lead_source_from"),
        ("lead", "0019_rename_assinged_to_lead_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="lead_source",
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.lead_source",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_source_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.lead_source_from",
            ),
        ),
    ]
