# Generated by Django 5.1.2 on 2024-12-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_lead_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='stage',
        ),
    ]
