# Generated by Django 5.1.2 on 2024-12-10 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lead_source_from_source'),
        ('lead', '0022_remove_opportunity_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.stage'),
        ),
    ]
