# Generated by Django 5.1.2 on 2024-12-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0024_lead_status_lead_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.contact'),
        ),
        migrations.AlterField(
            model_name='log',
            name='logtype',
            field=models.CharField(choices=[('Call', 'Call'), ('Meeting', 'Meeting'), ('Email', 'Email'), ('Others', 'Others')], default='Call', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10),
        ),
    ]
