# Generated by Django 5.1.2 on 2024-12-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0026_alter_log_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
            preserve_default=False,
        ),
    ]
