# Generated by Django 5.1.2 on 2024-12-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0027_alter_opportunity_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.lead'),
        ),
    ]
