# Generated by Django 5.1.2 on 2024-12-30 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0029_lead_bucket_opportunity_lead_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead.lead",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="logtype",
            field=models.CharField(
                choices=[
                    ("Call", "Call"),
                    ("Opportunity", "Opportunity"),
                    ("Email", "Email"),
                    ("Others", "Others"),
                ],
                default="Call",
                max_length=30,
            ),
        ),
    ]
