# Generated by Django 5.1.2 on 2024-12-31 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_lead_source_from_source"),
        ("lead", "0031_remove_lead_company_email_remove_lead_company_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="lead_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.lead_source",
            ),
        ),
    ]
