# Generated by Django 5.1.2 on 2024-12-31 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0032_contact_lead_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead.department",
            ),
        ),
    ]
