# Generated by Django 5.1.2 on 2024-12-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0033_alter_contact_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
