# Generated by Django 5.1.2 on 2024-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0034_task_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="status_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
