# Generated by Django 5.1.2 on 2025-01-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0035_lead_remark_lead_status_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
