# Generated by Django 5.1.2 on 2025-01-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_city"),
        ("lead", "0036_lead_address_lead_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.city",
            ),
        ),
    ]
