# Generated by Django 5.1.2 on 2025-01-02 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0037_alter_lead_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="city",
        ),
    ]
