# Generated by Django 5.1.2 on 2025-01-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_city"),
        ("lead", "0040_alter_lead_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="lead_source_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.lead_source_from",
            ),
        ),
    ]
