# Generated by Django 5.1.2 on 2025-01-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_city"),
        ("lead", "0043_alter_opportunity_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="currency_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.country",
            ),
        ),
    ]
