# Generated by Django 5.1.2 on 2025-01-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0045_alter_task_task_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_leads",
                to="lead.lead",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_logs",
                to="lead.contact",
            ),
        ),
    ]
