# Generated by Django 5.1.2 on 2025-01-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0047_remove_log_logtype_log_lead_log_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task_assignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_task_assignments",
                to="lead.task",
            ),
        ),
    ]
