# Generated by Django 5.1.2 on 2025-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0048_alter_task_assignment_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
