# Generated by Django 5.1.2 on 2025-01-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0049_contact_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="source_from",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
