# Generated by Django 5.1.2 on 2025-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0050_contact_source_from_alter_contact_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (" Call", " Call"),
                    (" Follow Up", " Follow Up"),
                    (" To Do", " To Do"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
