# Generated by Django 5.1.2 on 2025-01-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0051_log_log_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tasktype",
            new_name="task_creation_type",
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Call", "Call"),
                    ("Follow Up", "Follow Up"),
                    ("To Do", "To Do"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="log_type",
            field=models.CharField(
                blank=True,
                choices=[("Call", "Call"), ("Meeting", "Meeting"), ("Email", "Email")],
                max_length=20,
                null=True,
            ),
        ),
    ]
