# Generated by Django 5.1.2 on 2025-01-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0052_rename_tasktype_task_task_creation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
