# Generated by Django 5.1.2 on 2025-01-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0053_department_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead_status",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
