# Generated by Django 5.1.2 on 2025-01-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0055_alter_contact_email_id_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
