# Generated by Django 5.1.2 on 2025-01-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0058_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_status',
        ),
        migrations.RemoveField(
            model_name='log',
            name='lead_log_status',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.opportunity_status'),
        ),
    ]
