# Generated by Django 5.1.2 on 2025-01-31 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0060_lead_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='opportunity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.opportunity_status'),
        ),
    ]
