# Generated by Django 5.1.2 on 2025-01-31 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_stage_probability'),
        ('lead', '0061_log_opportunity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='opportunity_status',
        ),
        migrations.AlterField(
            model_name='log',
            name='log_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.log_stage'),
        ),
    ]
