# Generated by Django 5.1.2 on 2025-01-31 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0062_remove_log_opportunity_status_alter_log_log_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='opportunity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.opportunity_status'),
        ),
    ]
