# Generated by Django 5.1.2 on 2025-02-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0063_log_opportunity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities_leads', to='lead.lead'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
