# Generated by Django 5.1.2 on 2025-02-03 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0065_alter_opportunity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='status_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
