# Generated by Django 5.1.2 on 2025-02-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0069_taskconversationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconversationlog',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
