# Generated by Django 5.1.2 on 2025-02-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0070_taskconversationlog_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconversationlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_conversation_logs', to='lead.task'),
        ),
    ]
