# Generated by Django 5.1.2 on 2025-02-18 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0071_alter_taskconversationlog_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskconversationlog',
            name='viewed',
        ),
        migrations.AddField(
            model_name='taskconversationlog',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_task_conversation_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
