# Generated by Django 5.1.2 on 2025-02-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0072_remove_taskconversationlog_viewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead_status'),
        ),
    ]
