# Generated by Django 5.1.2 on 2025-02-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0073_alter_opportunity_opportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='opportunity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead_status'),
        ),
    ]
