# Generated by Django 5.1.2 on 2025-02-20 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0074_alter_log_opportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='opportunity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.opportunity_status'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.opportunity_status'),
        ),
    ]
