# Generated by Django 5.1.2 on 2025-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0077_opportunity_opportunity_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status_date',
            field=models.DateField(),
        ),
    ]
