# Generated by Django 5.1.2 on 2025-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0078_alter_opportunity_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
