# Generated by Django 5.1.2 on 2025-02-22 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0079_alter_opportunity_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
