# Generated by Django 5.1.2 on 2025-02-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0080_alter_opportunity_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
