# Generated by Django 5.1.2 on 2025-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0081_alter_opportunity_opportunity_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
