# Generated by Django 5.1.6 on 2025-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0083_alter_lead_address_alter_lead_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead_assignment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead_status",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="opportunity_status",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
