# Generated by Django 5.1.2 on 2025-03-10 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0083_alter_lead_address_alter_lead_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.taskconversationlog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
        migrations.AddField(
            model_name='notification',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.opportunity'),
        ),
        migrations.AddField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.task'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
