# Generated by Django 5.1.6 on 2025-03-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0084_lead_assignment_text_alter_lead_status_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead.lead",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead.task",
            ),
        ),
    ]
