# Generated by Django 5.1.6 on 2025-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0085_notification_assigned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="updated_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
