# Generated by Django 5.1.6 on 2025-03-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0085_notification_lead_notification_opportunity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
