# Generated by Django 5.1.6 on 2025-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0086_contact_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
