# Generated by Django 5.1.6 on 2025-03-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead", "0086_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lead.taskconversationlog",
            ),
        ),
    ]
