# Generated by Django 5.1.2 on 2025-04-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0086_contact_assignment'),
        ('lead', '0088_alter_contact_created_on'),
    ]

    operations = [
    ]
