# Generated by Django 5.1.2 on 2025-04-01 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0089_merge_20250401_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_assignment',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.contact'),
        ),
    ]
