# Generated by Django 5.1.2 on 2025-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0089_merge_20250401_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
