# Generated by Django 5.1.2 on 2025-04-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0092_delete_contact_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.contact'),
        ),
    ]
