# Generated by Django 5.1.2 on 2025-04-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0090_alter_contact_created_on'),
        ('lead', '0094_contact_assigned_to'),
    ]

    operations = [
    ]
