# Generated by Django 5.2 on 2025-11-10 04:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_usertarget_user'),
        ('lead', '0098_alter_contact_created_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='UserProfile',
        ),
    ]
