# Generated by Django 4.2.11 on 2025-11-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0099_rename_employee_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='joined_on',
        ),
    ]
