# Generated by Django 4.2.11 on 2025-11-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0101_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
