# Generated by Django 4.2.11 on 2025-11-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0102_remove_userprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
