# Generated by Django 4.2.11 on 2025-11-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0103_log_new_value_log_old_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
