# Generated by Django 4.2.11 on 2025-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0104_opportunity_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
