# Generated by Django 4.2.11 on 2025-11-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0104_opportunity_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='remark',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
