# Generated by Django 4.2.11 on 2025-11-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0105_alter_opportunity_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
