# Generated by Django 4.2.11 on 2025-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0106_alter_opportunity_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
