# Generated by Django 5.2 on 2025-11-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0107_alter_opportunity_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
