# Generated by Django 4.2.11 on 2025-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0108_lead_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead_assignment',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_assignment',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
