# Generated by Django 4.2.11 on 2026-03-02 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_alter_usertarget_user'),
        ('lead', '0110_contentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_content_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.department'),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='email_id',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.lead'),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lead_source'),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='lead_source_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lead_source_from'),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='source_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentlog',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact_status'),
        ),
        migrations.AlterField(
            model_name='contentlog',
            name='proposal',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('Contact', 'Contact')], default='draft', max_length=20),
        ),
    ]
