# Generated by Django 4.2.11 on 2026-03-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0111_contentlog_assigned_to_contentlog_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_type',
            field=models.CharField(blank=True, choices=[('Call', 'Call'), ('Meeting', 'Meeting'), ('Email', 'Email'), ('Contact', 'Contact')], max_length=20, null=True),
        ),
    ]
