# Generated by Django 5.2 on 2026-05-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0112_alter_log_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='google_calendar_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
