# Generated by Django 5.2 on 2026-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0113_task_deleted_task_google_calendar_synced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=512, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=512, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=512, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=512, null=True)),
                ('github_url', models.URLField(blank=True, max_length=512, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=512, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_status', models.CharField(blank=True, max_length=64, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=64, null=True)),
                ('formatted_address', models.TextField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=128, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=128, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=512, null=True)),
                ('organization', models.JSONField(blank=True, null=True)),
                ('employment_history', models.JSONField(blank=True, null=True)),
                ('departments', models.JSONField(blank=True, null=True)),
                ('subdepartments', models.JSONField(blank=True, null=True)),
                ('seniority', models.CharField(blank=True, max_length=128, null=True)),
                ('functions', models.JSONField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
