# Generated by Django 5.2 on 2026-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0114_apollolead'),
    ]

    operations = [
        migrations.AddField(
            model_name='apollolead',
            name='contact',
            field=models.BooleanField(default=False),
        ),
    ]
