# Generated by Django 5.2 on 2026-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0115_apollolead_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='apollo',
            field=models.BooleanField(default=False),
        ),
    ]
