# Generated by Django 5.2 on 2026-06-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0116_contact_apollo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloPagination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_titles', models.JSONField(blank=True, default=list, null=True)),
                ('person_locations', models.JSONField(blank=True, default=list, null=True)),
                ('organization_num_employees_ranges', models.JSONField(blank=True, default=list, null=True)),
                ('organization_industries', models.JSONField(blank=True, default=list, null=True)),
                ('page', models.IntegerField()),
                ('per_page', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apollo Pagination History',
                'db_table': 'apollo_pagination_history',
                'ordering': ['-created_on'],
            },
        ),
    ]
