# Generated by Django 5.2 on 2026-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0118_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
